"""
Packer Generator
Generates Packer templates to create VM images
"""

import json
import logging
import os
from typing import Dict, List, Any

logger = logging.getLogger(__name__)


class PackerGenerator:
    """Generates Packer templates for vSphere"""

    def __init__(self, analysis_data: Dict[str, Any], vsphere_template: str = None):
        self.data = analysis_data
        self.vsphere_template = vsphere_template or 'ubuntu-22.04-template'
        self.hostname = analysis_data.get('hostname', 'server')

    def generate(self, output_dir: str) -> str:
        """Generate all Packer files"""
        os.makedirs(output_dir, exist_ok=True)
        os.makedirs(os.path.join(output_dir, 'scripts'), exist_ok=True)
        os.makedirs(os.path.join(output_dir, 'http'), exist_ok=True)

        self._generate_packer_hcl(output_dir)
        self._generate_variables_hcl(output_dir)
        self._generate_auto_pkrvars(output_dir)
        self._generate_provisioning_scripts(output_dir)
        self._generate_cloud_init(output_dir)

        logger.info(f"Packer configuration generated in: {output_dir}")
        return output_dir

    def _get_packages_to_install(self) -> List[str]:
        """Get list of packages to install"""
        packages = []

        # From installed packages
        installed = self.data.get('files', {}).get('installed_packages', [])
        for pkg in installed:
            if pkg.get('manager') in ['apt', 'dpkg']:
                name = pkg.get('name', '')
                # Filter out common base packages
                if name and not any(x in name for x in ['linux-', 'libc', 'base-', 'ubuntu-']):
                    packages.append(name)

        return list(dict.fromkeys(packages))[:50]  # Dedupe and limit

    def _get_vm_specs(self) -> Dict:
        """Extract VM specifications"""
        resources = self.data.get('processes', {}).get('resource_usage', {})

        specs = {
            'cpus': 2,
            'memory': 4096,
            'disk_size': 50000
        }

        cpu = resources.get('cpu', {})
        memory = resources.get('memory', {})

        if cpu.get('count'):
            specs['cpus'] = cpu['count']
        if memory.get('total'):
            specs['memory'] = int(memory['total'] / 1024 / 1024)

        return specs

    def _generate_packer_hcl(self, output_dir: str) -> None:
        """Generate main Packer HCL configuration"""
        specs = self._get_vm_specs()

        content = f'''# Packer configuration for {self.hostname}
# Generated by System Analyzer

packer {{
  required_version = ">= 1.8.0"

  required_plugins {{
    vsphere = {{
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/vsphere"
    }}
  }}
}}

# Local variables
locals {{
  build_timestamp = formatdate("YYYYMMDD-hhmmss", timestamp())
  vm_name         = "${{var.vm_name_prefix}}-${{local.build_timestamp}}"
}}

# vSphere ISO builder
source "vsphere-iso" "base" {{
  # vCenter connection
  vcenter_server      = var.vsphere_server
  username            = var.vsphere_user
  password            = var.vsphere_password
  insecure_connection = var.vsphere_insecure

  # VM location
  datacenter = var.vsphere_datacenter
  cluster    = var.vsphere_cluster
  datastore  = var.vsphere_datastore
  folder     = var.vsphere_folder

  # VM settings
  vm_name              = local.vm_name
  guest_os_type        = var.guest_os_type
  CPUs                 = var.vm_cpus
  RAM                  = var.vm_memory
  RAM_reserve_all      = false
  disk_controller_type = ["pvscsi"]
  firmware             = "efi"

  storage {{
    disk_size             = var.vm_disk_size
    disk_thin_provisioned = true
  }}

  network_adapters {{
    network      = var.vsphere_network
    network_card = "vmxnet3"
  }}

  # ISO settings
  iso_paths = var.iso_paths

  # Boot settings
  boot_order   = "disk,cdrom"
  boot_wait    = "5s"
  boot_command = var.boot_command

  # HTTP server for cloud-init
  http_directory = "http"
  http_port_min  = 8000
  http_port_max  = 8100

  # SSH settings
  ssh_username         = var.ssh_username
  ssh_password         = var.ssh_password
  ssh_timeout          = "30m"
  ssh_handshake_attempts = 100

  # Shutdown
  shutdown_command = "echo '${{var.ssh_password}}' | sudo -S shutdown -P now"
  shutdown_timeout = "10m"

  # Convert to template
  convert_to_template = true
}}

# Build definition
build {{
  name    = "{self.hostname}-template"
  sources = ["source.vsphere-iso.base"]

  # Wait for cloud-init to complete
  provisioner "shell" {{
    inline = [
      "while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 5; done"
    ]
  }}

  # Run setup script
  provisioner "shell" {{
    scripts = [
      "scripts/setup.sh"
    ]
    execute_command = "echo '${{var.ssh_password}}' | sudo -S sh -c '{{{{ .Path }}}}'"
  }}

  # Run application setup
  provisioner "shell" {{
    scripts = [
      "scripts/install-packages.sh"
    ]
    execute_command = "echo '${{var.ssh_password}}' | sudo -S sh -c '{{{{ .Path }}}}'"
  }}

  # Clean up
  provisioner "shell" {{
    scripts = [
      "scripts/cleanup.sh"
    ]
    execute_command = "echo '${{var.ssh_password}}' | sudo -S sh -c '{{{{ .Path }}}}'"
  }}

  post-processor "manifest" {{
    output     = "manifest.json"
    strip_path = true
  }}
}}
'''

        with open(os.path.join(output_dir, 'vsphere.pkr.hcl'), 'w') as f:
            f.write(content)

    def _generate_variables_hcl(self, output_dir: str) -> None:
        """Generate variables definition file"""
        specs = self._get_vm_specs()

        content = f'''# Variable definitions for Packer
# Generated by System Analyzer

# vSphere Connection
variable "vsphere_server" {{
  type        = string
  description = "vSphere server address"
}}

variable "vsphere_user" {{
  type        = string
  description = "vSphere username"
}}

variable "vsphere_password" {{
  type        = string
  description = "vSphere password"
  sensitive   = true
}}

variable "vsphere_insecure" {{
  type        = bool
  description = "Allow insecure connection to vSphere"
  default     = true
}}

# vSphere Infrastructure
variable "vsphere_datacenter" {{
  type        = string
  description = "vSphere datacenter"
  default     = "Datacenter"
}}

variable "vsphere_cluster" {{
  type        = string
  description = "vSphere cluster"
  default     = "Cluster"
}}

variable "vsphere_datastore" {{
  type        = string
  description = "vSphere datastore"
  default     = "datastore1"
}}

variable "vsphere_network" {{
  type        = string
  description = "vSphere network"
  default     = "VM Network"
}}

variable "vsphere_folder" {{
  type        = string
  description = "vSphere folder for templates"
  default     = "Templates"
}}

# VM Configuration
variable "vm_name_prefix" {{
  type        = string
  description = "Prefix for VM name"
  default     = "{self.hostname}-template"
}}

variable "guest_os_type" {{
  type        = string
  description = "Guest OS type"
  default     = "ubuntu64Guest"
}}

variable "vm_cpus" {{
  type        = number
  description = "Number of CPUs"
  default     = {specs['cpus']}
}}

variable "vm_memory" {{
  type        = number
  description = "Memory in MB"
  default     = {specs['memory']}
}}

variable "vm_disk_size" {{
  type        = number
  description = "Disk size in MB"
  default     = {specs['disk_size']}
}}

# ISO Configuration
variable "iso_paths" {{
  type        = list(string)
  description = "ISO datastore paths"
  default     = ["[datastore1] ISO/ubuntu-22.04-live-server-amd64.iso"]
}}

# Boot Command
variable "boot_command" {{
  type        = list(string)
  description = "Boot command for autoinstall"
  default     = [
    "<esc><wait>",
    "e<wait>",
    "<down><down><down><end>",
    " autoinstall ds=nocloud-net;s=http://{{{{ .HTTPIP }}}}:{{{{ .HTTPPort }}}}/",
    "<F10>"
  ]
}}

# SSH Configuration
variable "ssh_username" {{
  type        = string
  description = "SSH username"
  default     = "ubuntu"
}}

variable "ssh_password" {{
  type        = string
  description = "SSH password"
  default     = "ubuntu"
  sensitive   = true
}}
'''

        with open(os.path.join(output_dir, 'variables.pkr.hcl'), 'w') as f:
            f.write(content)

    def _generate_auto_pkrvars(self, output_dir: str) -> None:
        """Generate example variables file"""
        content = '''# Example Packer variables
# Copy to auto.pkrvars.hcl and fill in values

vsphere_server   = "vcenter.example.com"
vsphere_user     = "administrator@vsphere.local"
vsphere_password = "your-password-here"

vsphere_datacenter = "Datacenter"
vsphere_cluster    = "Cluster"
vsphere_datastore  = "datastore1"
vsphere_network    = "VM Network"
vsphere_folder     = "Templates"

ssh_username = "ubuntu"
ssh_password = "ubuntu"

iso_paths = ["[datastore1] ISO/ubuntu-22.04-live-server-amd64.iso"]
'''

        with open(os.path.join(output_dir, 'auto.pkrvars.hcl.example'), 'w') as f:
            f.write(content)

    def _generate_provisioning_scripts(self, output_dir: str) -> None:
        """Generate provisioning shell scripts"""
        scripts_dir = os.path.join(output_dir, 'scripts')

        # Setup script
        setup_content = '''#!/bin/bash
# Base system setup
set -e

echo "==> Updating system packages"
apt-get update
apt-get upgrade -y

echo "==> Installing base packages"
apt-get install -y \\
    curl \\
    wget \\
    vim \\
    git \\
    htop \\
    net-tools \\
    ca-certificates \\
    gnupg \\
    lsb-release \\
    software-properties-common

echo "==> Configuring system"
# Set timezone
timedatectl set-timezone UTC

# Enable NTP
systemctl enable systemd-timesyncd
systemctl start systemd-timesyncd

echo "==> Base setup complete"
'''

        with open(os.path.join(scripts_dir, 'setup.sh'), 'w') as f:
            f.write(setup_content)

        # Package installation script
        packages = self._get_packages_to_install()
        packages_content = '''#!/bin/bash
# Install application packages
set -e

echo "==> Installing application packages"

'''
        if packages:
            packages_content += f'''apt-get install -y \\
    {' '.join(packages[:30])}

'''

        packages_content += '''
# Install any pip packages
if command -v pip3 &> /dev/null; then
    echo "==> pip3 available for Python packages"
fi

echo "==> Package installation complete"
'''

        with open(os.path.join(scripts_dir, 'install-packages.sh'), 'w') as f:
            f.write(packages_content)

        # Cleanup script
        cleanup_content = '''#!/bin/bash
# Cleanup script for template creation
set -e

echo "==> Cleaning up"

# Clean apt cache
apt-get autoremove -y
apt-get clean
rm -rf /var/lib/apt/lists/*

# Clear machine-id
truncate -s 0 /etc/machine-id
rm -f /var/lib/dbus/machine-id
ln -s /etc/machine-id /var/lib/dbus/machine-id

# Clear SSH host keys
rm -f /etc/ssh/ssh_host_*

# Clear logs
find /var/log -type f -exec truncate -s 0 {} \\;

# Clear temp
rm -rf /tmp/*
rm -rf /var/tmp/*

# Clear bash history
unset HISTFILE
rm -f /root/.bash_history
rm -f /home/*/.bash_history

# Cloud-init clean
if command -v cloud-init &> /dev/null; then
    cloud-init clean --logs --seed
fi

echo "==> Cleanup complete"
'''

        with open(os.path.join(scripts_dir, 'cleanup.sh'), 'w') as f:
            f.write(cleanup_content)

    def _generate_cloud_init(self, output_dir: str) -> None:
        """Generate cloud-init configuration for autoinstall"""
        http_dir = os.path.join(output_dir, 'http')

        # user-data
        user_data = '''#cloud-config
autoinstall:
  version: 1
  locale: en_US.UTF-8
  keyboard:
    layout: us
  identity:
    hostname: template
    username: ubuntu
    password: "$6$rounds=4096$xyz$hashed_password_here"
  ssh:
    install-server: true
    allow-pw: true
  storage:
    layout:
      name: lvm
  packages:
    - open-vm-tools
    - cloud-init
  late-commands:
    - echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/ubuntu
'''

        with open(os.path.join(http_dir, 'user-data'), 'w') as f:
            f.write(user_data)

        # meta-data (empty but required)
        with open(os.path.join(http_dir, 'meta-data'), 'w') as f:
            f.write('')
